Do not show user name , password  on User Index Page

For Users :

First Name , Last Name shuld only take alphbets and spaces

For Batch 

Batch Code : Batch Code should de autogenerated
Number of Seats should be in range 5 to 10 
Date of Start should be only after current Date and should be less than 2 months 

For Course: 

Course Code should be autogenerated  
One Course Name should not be added again


Login should be allowed only for 3 times after that display message "Please try after some time"

Create a Home Page which shows following links

List of Courses
List of Running Batches
List of all Users


